"""Embedded Vastu Shastra principles and foundational knowledge."""

VASTU_PRINCIPLES = {
    "north_prosperity": {
        "name": "North = Prosperity & Career",
        "description": "North direction is governed by Kubera (god of wealth) and represents financial prosperity, career growth, and opportunities",
        "key_points": [
            "Keep North lighter and more open",
            "Avoid heavy structures in North",
            "Place water elements in North",
            "North entrance is auspicious for commercial establishments",
        ],
        "elements": ["Water"],
        "colors": ["White", "Black", "Blue"],
        "remedies": ["Water fountain", "Mirror", "Light colors"],
    },
    "east_health": {
        "name": "East = Health & Family",
        "description": "East direction is governed by Surya (Sun god) and represents health, vitality, new beginnings, and family harmony",
        "key_points": [
            "East should be open and bright",
            "Get morning sunlight from East",
            "Avoid blocking East windows",
            "Place senior family members in East-facing rooms",
        ],
        "elements": ["Air"],
        "colors": ["Green", "White", "Golden"],
        "remedies": ["Morning sunlight", "Plants", "Crystal balls"],
    },
    "south_courage": {
        "name": "South = Courage & Stability",
        "description": "South direction is governed by Yama (god of death/justice) and represents stability, reputation, and courage",
        "key_points": [
            "South wall should be stronger/higher",
            "Heavy furniture in South is favorable",
            "Avoid openings in South wall",
            "Good for store room or safe deposit",
        ],
        "elements": ["Fire"],
        "colors": ["Red", "Orange", "Pink"],
        "remedies": ["Heavy furnishings", "Walls", "Fire element decorations"],
    },
    "west_support": {
        "name": "West = Support & Help",
        "description": "West direction is governed by Varuna (god of water/ocean) and represents support, helpful people, and completion",
        "key_points": [
            "West should be slightly elevated",
            "Avoid water in West",
            "Good for workshop or creative space",
            "West entrance suitable for spiritual centers",
        ],
        "elements": ["Metal/Earth"],
        "colors": ["White", "Gray", "Yellow"],
        "remedies": ["Metal elements", "Symbols", "Art installations"],
    },
    "northeast_wisdom": {
        "name": "Northeast = Wisdom & Spirituality",
        "description": "Northeast (Ishan) is the most sacred direction, governed by Ishana (manifestation of Shiva) and represents knowledge, wisdom, and spiritual growth",
        "key_points": [
            "Keep Northeast clean and light",
            "Northeast should be highest point",
            "Excellent for prayer room or meditation space",
            "Avoid toilets and drains in Northeast",
            "Water in Northeast is highly auspicious",
        ],
        "elements": ["Ether/Water"],
        "colors": ["White", "Light colors"],
        "remedies": ["Prayer room", "Water feature", "Crystals", "Fresh flowers"],
    },
    "southeast_passion": {
        "name": "Southeast = Passion & Energy",
        "description": "Southeast (Agni) is governed by Agni (god of fire) and represents energy, passion, cooking, and transformation",
        "key_points": [
            "Ideal location for kitchen",
            "Southeast should have good ventilation",
            "Fire element is naturally strong here",
            "Avoid water features in Southeast",
            "Good for heat-generating activities",
        ],
        "elements": ["Fire"],
        "colors": ["Red", "Orange", "Pink"],
        "remedies": ["Kitchen appliances", "Bright lighting", "Fire symbols"],
    },
    "southwest_grounding": {
        "name": "Southwest = Grounding & Stability",
        "description": "Southwest (Nairiti) is governed by Nirtya (a form of Shiva) and represents grounding, stability, and strength",
        "key_points": [
            "Southwest should be heavier/solid",
            "Master bedroom ideal in Southwest",
            "Avoid openings in Southwest",
            "Good for storage and valuables",
            "Should be well-supported and protected",
        ],
        "elements": ["Earth"],
        "colors": ["Brown", "Red", "Yellow"],
        "remedies": ["Heavy furniture", "Storage", "Solid structures"],
    },
    "northwest_movement": {
        "name": "Northwest = Movement & Change",
        "description": "Northwest (Vayavya) is governed by Vayu (god of wind/air) and represents movement, change, and travel",
        "key_points": [
            "Good for guest room",
            "Avoid important activities here",
            "Northwest should be lighter",
            "Suitable for servant quarters",
            "Air circulation important",
        ],
        "elements": ["Air"],
        "colors": ["Green", "White", "Gray"],
        "remedies": ["Air circulation", "Plants", "Light furnishings"],
    },
    "center_balance": {
        "name": "Center (Brahmasthan) = Balance & Life Force",
        "description": "The center of the space represents Brahma (creator) and is the source of vital life energy. This is the most important point",
        "key_points": [
            "Center should be open and uncluttered",
            "Never build heavy structures in center",
            "Keep center lighter than other areas",
            "Avoid kitchen or toilet in center",
            "Center circulation maintains energy flow",
            "Heart of the home - influences entire space",
        ],
        "elements": ["Ether/All"],
        "colors": ["Yellow", "White"],
        "remedies": ["Open space", "Light fixtures", "Courtyard", "Atrium"],
    },
    "entrance_auspiciousness": {
        "name": "Main Entrance = Welcoming Auspicious Energy",
        "description": "The entrance is where energy enters the space and sets the tone for the entire environment",
        "key_points": [
            "Entrance should be clean and well-lit",
            "Entrance from North or East is most auspicious",
            "Avoid entrance in Southwest",
            "Should be wider than back entrance",
            "Entrance size matters - not too small",
            "Doors should open fully without obstruction",
        ],
        "elements": ["Air", "Water"],
        "colors": ["Light colors", "White", "Green"],
        "remedies": ["Good lighting", "Plants", "Symbols", "Clean space"],
    },
    "staircase_flow": {
        "name": "Staircase = Energy Flow & Movement",
        "description": "Staircases direct the flow of energy between levels and should be positioned carefully",
        "key_points": [
            "Clockwise spiral is auspicious",
            "Counter-clockwise spiral creates negative energy",
            "Stairs in center are unfavorable",
            "Avoid stairs in Northeast",
            "South and West are good locations",
            "Stairs below ground level should have light",
        ],
        "elements": ["Air/Water"],
        "colors": ["Neutral colors"],
        "remedies": ["Proper lighting", "Mirrors", "Paintings"],
    },
}

ROOM_TYPE_GUIDELINES = {
    "bedroom": {
        "best_directions": ["South", "Southwest"],
        "avoid": ["Northeast", "East"],
        "shape": "Square or rectangle",
        "window_placement": "South or West",
        "color": "Light, soothing colors",
        "furniture": "Heavy, grounding furniture",
    },
    "kitchen": {
        "best_directions": ["Southeast", "South"],
        "avoid": ["North", "Northeast"],
        "shape": "Square or rectangle",
        "window_placement": "East or North",
        "color": "Orange, red, yellow",
        "furniture": "Stove in Southeast corner",
    },
    "bathroom": {
        "best_directions": ["South", "West"],
        "avoid": ["Northeast"],
        "shape": "Square",
        "window_placement": "South or West",
        "color": "Light colors, white",
        "furniture": "Minimal, functional",
    },
    "pooja_room": {
        "best_directions": ["Northeast"],
        "avoid": ["South", "Southwest"],
        "shape": "Square",
        "window_placement": "East or North",
        "color": "White, light colors",
        "furniture": "Elevated altar, minimal furniture",
    },
    "study": {
        "best_directions": ["East", "Northeast"],
        "avoid": ["South", "Southwest"],
        "shape": "Square or rectangle",
        "window_placement": "East or North",
        "color": "Light, calming colors",
        "furniture": "Desk facing East or North",
    },
    "living_room": {
        "best_directions": ["North", "East"],
        "avoid": ["Southwest"],
        "shape": "Square or rectangle",
        "window_placement": "North or East",
        "color": "Light, warm colors",
        "furniture": "Central seating, open layout",
    },
}

COMMON_VASTU_DEFECTS = {
    "missing_northeast": {
        "problem": "Entire Northeast corner is cut off or missing",
        "impact": "Loss of wisdom, knowledge, and spiritual growth",
        "severity": "Critical",
        "remedies": ["Use mirrors to visually extend Northeast", "Place light and water elements", "Install crystal"],
    },
    "toilet_northeast": {
        "problem": "Toilet located in Northeast direction",
        "impact": "Severe negative energy, loss of prosperity",
        "severity": "Critical",
        "remedies": ["Shift toilet if possible", "Place mirrors to deflect energy", "Use salt to absorb negative energy"],
    },
    "kitchen_center": {
        "problem": "Kitchen located in the center (Brahmasthan)",
        "impact": "Disrupts life force energy, affects health and prosperity",
        "severity": "Critical",
        "remedies": ["Relocate kitchen", "Use red color to absorb fire", "Install healing crystals"],
    },
    "heavy_northeast": {
        "problem": "Heavy structures or furniture in Northeast",
        "impact": "Blocks flow of positive energy and wisdom",
        "severity": "High",
        "remedies": ["Lighten Northeast area", "Use mirrors and lights", "Remove heavy items"],
    },
    "southwest_open": {
        "problem": "Southwest is very open or has large windows",
        "impact": "Instability, lack of grounding",
        "severity": "High",
        "remedies": ["Add heavy furniture", "Use heavier curtains", "Install solid storage"],
    },
    "south_low": {
        "problem": "South wall is lower than North wall",
        "impact": "Loss of reputation and stability",
        "severity": "Medium",
        "remedies": ["Raise South wall if possible", "Add decorative elements", "Use earth tones"],
    },
}

REMEDIES_BY_TYPE = {
    "color": {
        "white": "Purity, peace, clarity",
        "yellow": "Wisdom, prosperity, happiness",
        "orange": "Energy, enthusiasm, creativity",
        "red": "Strength, courage, passion",
        "green": "Growth, health, renewal",
        "blue": "Calm, prosperity, knowledge",
        "black": "Strength, protection (limited use)",
        "brown": "Stability, grounding",
        "pink": "Love, harmony, compassion",
    },
    "element": {
        "water": "Prosperity, flow, cleansing",
        "fire": "Energy, transformation, passion",
        "earth": "Stability, grounding, support",
        "air": "Movement, clarity, communication",
        "ether": "Spirituality, connection, expansion",
    },
    "object": {
        "mirror": "Expansion, reflection, correction",
        "crystal": "Energy amplification, clarity",
        "wind_chime": "Air movement, sound healing",
        "plant": "Life force, growth, purification",
        "light": "Illumination, positive energy",
        "fountain": "Water flow, prosperity",
        "mandala": "Energy balancing, spiritual connection",
    },
}
